version: '3.4'

services:
  richardwettstone-host:
    image: jlind/richardwettstone-host
    build:
      context: ./
      args:
        baseurl: http://$DOMAIN
    networks:
      - net
    environment:
      VIRTUAL_HOST: $DOMAIN
      VIRTUAL_PORT: 80
    # volumes:
    #   - ./output/:/usr/share/nginx/html:ro
    # ports:
    #   - 80:80

  dickwettstone-host:
    image: nginx:alpine
    environment:
      VIRTUAL_HOST: $OLD_DOMAIN
      VIRTUAL_PORT: 80
    networks:
      - net
    volumes:
      - ./container_conf.d/dickwettstone-host/00_redirect.conf:/etc/nginx/conf.d/00_redirect.conf:ro
  
  # richardwettstone-host:
  #   image: jlind/richardwettstone-host
  #   build:
  #     context: ./
  #   networks:
  #     - net
  #   environment:
  #     VIRTUAL_HOST: $SECONDARY_DOMAIN
  #     VIRTUAL_PORT: 80

networks:
  net:
    external:
      name: docker-reverse-proxy_net