version: '3.4'

services:
  richardwettstone-host:
    image: jlind/richardwettstone-host
    build:
      context: ./
      args:
        baseurl: http://$DOMAIN
    networks:
      - net
    environment:
      VIRTUAL_HOST: $DOMAIN
      VIRTUAL_PORT: 80

networks:
  net:
    external:
      name: docker-reverse-proxy_net
