version: '3.4'

services:
  host:
    image: jlind/wettstone-host
    build:
      context: ./
    networks:
      - net
    environment:
      VIRTUAL_HOST: $DOMAIN
      VIRTUAL_PORT: 80
    # volumes:
    #   - ./output/:/usr/share/nginx/html:ro
    # ports:
    #   - 80:80

networks:
  net:
    external:
      name: docker-reverse-proxy_net