# baseurl = "http://richardwettstone.com"
# baseurl = 'https://richardwettstone.jdev.pw'
title = "Richard P. Wettstone, Ed.D. - Licensed Professional Counselor"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Richard P. Wettstone Ed.D." # This should be fixed, author is not a descriptive name for this variable
    description = "Richard Wettstone is a Licensed Professional Counselor based in Harrisonburg, VA. Specialties include relationship issues, all types of addictions, stress and anger management, depression, and PTSD. Richard Wettstone EdD is trained and certified in hypnosis, which is useful for those interested in specific issues like smoking cessation."
    keywords = "lpc,licensed,professional,counselor"
    info = "Licensed Professional Counselor"

    hideCredits = true
    hideCopyright = true

    alturl = "https://dickwettstone.com"

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Phone: (540) 434-9430"
    weight = 1
    url = "tel:+1-540-434-9430"
[[params.social]]
    name = "Email: lpcrpw@gmail.com"
    weight = 2
    url = "mailto:lpcrpw@gmail.com"
[[params.social]]
    name = "Fax: (540) 434-8100"
    weight = 3
    url = "fax:+1-540-434-8100"

# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "/about/"
[[menu.main]]
    name = "Location"
    weight = 1
    url = "/location"
